### ISSUE TITLE
[Bug] recipe does not make Oscar

### ISSUE THREAD

**Issue by TheDarkPreacher** [GrimCo/Oscars#2]
Version: 1.0.0
Forge ver: 31.1.18

What is expected: 8 iron around an eye of ender in a crafting table makes an Oscar
What happens: 8 iron around an eye of ender produces nothing.

Steps to reproduce: Install mod, get 8 iron, 1 eye of ender, surround eye with iron in 3x3 crafting grid, check result.

Bug found in CipraTech ver. 1.0.4

![2020-03-09_20 44 59](https://user-images.githubusercontent.com/15058826/76271732-6aaacd00-6247-11ea-9bba-5d702d9295ef.png)

**Comment by mallrat208** [comment]
This is fixed with version 1.0.1
